# Generated by Django 5.1.2 on 2024-10-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
